const { GoogleGenerativeAI } = require("@google/generative-ai");

const analyzeResume = async (req, res) => {
  try {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_KEY);
    const resumeData = req.body;
    
    if (!resumeData) {
      return res.status(400).json({ error: "No resume data provided" });
    }

    const systemInstruction = `
You are a professional resume reviewer. Provide concise, actionable feedback.

CRITICAL RULES:
1. Provide ONLY plain text analysis - NO markdown formatting, NO ** bold text, NO HTML
2. Keep feedback brief and to the point - max 2 sentences per point
3. NO promotional content whatsoever
4. Focus on the most important improvements only

FORMAT YOUR RESPONSE EXACTLY AS:

STRENGTHS:
• [Brief strength in 1-2 sentences]
• [Brief strength in 1-2 sentences] 
• [Brief strength in 1-2 sentences]

AREAS FOR IMPROVEMENT:
• [Issue]: [Brief solution in 1-2 sentences]
• [Issue]: [Brief solution in 1-2 sentences]
• [Issue]: [Brief solution in 1-2 sentences]

RECOMMENDATIONS:
• [Specific action to take in 1-2 sentences]
• [Specific action to take in 1-2 sentences]
• [Specific action to take in 1-2 sentences]

Keep each point concise and actionable. Use simple bullet points with no special formatting.
`.trim();

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      systemInstruction
    });

    const response = await model.generateContent(
      `Resume data:\n${JSON.stringify(resumeData, null, 2)}`
    );

    const analysisText = response.response.text().trim() || 
      "Unable to analyze resume. Please ensure all required fields are filled and try again.";

    return res.status(200).json({ analysis: analysisText });

  } catch (error) {
    console.error("Resume Analysis Error:", error);
    return res.status(500).json({ 
      error: "Failed to analyze resume", 
      details: error.message 
    });
  }
};

const generatePDF = async (req, res) => {
  try {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_KEY);
    const resumeData = req.body;

    const systemInstruction = `
You are a professional resume writer. Follow these rules:

1. Convert the provided resume data into a polished HTML resume
2. Use clean, professional styling with modern CSS
3. Structure with sections: Header, Summary, Experience, Education, Skills, Projects
4. Apply responsive design principles
5. Include subtle animations for professionalism
6. Format dates consistently (MM/YYYY)
7. Add a "Generated by Nexus" footer
8. Output ONLY the HTML code with embedded CSS
9. Use a professional color scheme (blues and grays)
10. Make sure it looks good when printed to PDF
`.trim();

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      systemInstruction
    });

    const response = await model.generateContent(
      `Resume data:\n${JSON.stringify(resumeData, null, 2)}`
    );

    const resumeHTML = response.response.text().trim() || 
      "<h1 class='text-red-500'>Error generating resume</h1>";

    return res.status(200).json({ html: resumeHTML });

  } catch (error) {
    console.error("PDF Generation Error:", error);
    return res.status(500).json({ 
      error: "Failed to generate PDF", 
      details: error.message 
    });
  }
};

const improveContent = async (req, res) => {
  try {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_KEY);
    const { content, section, field, context } = req.body;
    
    if (!content || !section || !field) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const systemInstruction = `
You are a professional resume content improvement specialist. Follow these rules:

1. Improve the provided content to make it more impactful and professional
2. Use action-oriented language and quantifiable achievements
3. Make it ATS-friendly with relevant keywords
4. Keep the same general length and structure
5. Focus on impact and results
6. Return ONLY the improved content - no explanations or additional text
7. For experience descriptions: Start with strong action verbs, include metrics
8. For project descriptions: Highlight technical skills, show problem-solving
9. For summaries: Create compelling value proposition with key strengths
10. For education: Include relevant coursework, achievements, skills developed
`.trim();

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      systemInstruction
    });

    const response = await model.generateContent(
      `Content to improve: "${content}"\nSection: ${section}\nField: ${field}\nContext: ${JSON.stringify(context, null, 2)}`
    );

    const improvedContent = response.response.text().trim() || 
      "Unable to improve content. Please try again.";

    return res.status(200).json({ improvedContent });

  } catch (error) {
    console.error("Content Improvement Error:", error);
    return res.status(500).json({ 
      error: "Failed to improve content", 
      details: error.message 
    });
  }
};

const getImprovementSuggestions = async (req, res) => {
  try {
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_KEY);
    const { content, section, field, context } = req.body;
    
    if (!content || !section || !field) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const systemInstruction = `
You are a professional resume improvement advisor. Follow these rules:

1. Analyze the provided content and give exactly 3 improvement suggestions
2. Each suggestion should be specific and actionable
3. Format your response exactly as:
   <div class="improvement-suggestions">
     <div class="suggestion-item">
       <span class="bullet">●</span>
       <strong>First improvement suggestion</strong>
     </div>
     <div class="suggestion-item">
       <span class="bullet">●</span>
       <strong>Second improvement suggestion</strong>
     </div>
     <div class="suggestion-item">
       <span class="bullet">●</span>
       <strong>Third improvement suggestion</strong>
     </div>
   </div>

4. Make suggestions relevant to the section and field provided
5. Focus on professional impact and ATS optimization
6. Keep each suggestion concise but specific
7. Always return exactly 3 suggestions with bold circle symbols
8. Use HTML formatting only as shown above
`.trim();

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      systemInstruction
    });

    const response = await model.generateContent(
      `Analyze this content: "${content}"\nSection: ${section}\nField: ${field}\nContext: ${JSON.stringify(context, null, 2)}`
    );

    const suggestions = response.response.text().trim() || 
      "<div class='text-red-500'>Unable to generate suggestions. Please try again.</div>";

    return res.status(200).json({ suggestions });

  } catch (error) {
    console.error("Improvement Suggestions Error:", error);
    return res.status(500).json({ 
      error: "Failed to generate suggestions", 
      details: error.message 
    });
  }
};


module.exports = {getImprovementSuggestions,improveContent,generatePDF,analyzeResume}